---
services:
  converter:
    image: eriklysoe/converter:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: converter
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MAX_FILE_SIZE=4000  # in MB
      - WORKER_TIMEOUT=14400  # gunicorn worker timeout in seconds (4 hours)
    volumes:
      - ./config:/config
      - ./config/temp:/tmp/converter
    ports:
      - "7391:7391"
    restart: unless-stopped
