---
services:
  converter:
    image: ghcr.io/eriklysoe/converter:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: converter
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MAX_FILE_SIZE=50  # in MB
      - ADMIN_USER=changeme
      - ADMIN_PASS=changeme
    volumes:
      - ./config:/config
      - ./config/temp:/tmp/converter
    ports:
      - "7391:7391"
    restart: unless-stopped
